export const addresses = [
  {
    id: 1,
    sym: "bnb",
    name: "BNB",
    address: "0xf3c93D9498644646EA389134A8Dd2AC1B48a1f73",
    network: "bnb",
    img: "/bnb.png",
    logo: "https://w7.pngwing.com/pngs/1007/775/png-transparent-bnb-cryptocurrencies-icon.png",
  },

  {
    id: 2,
    sym: "ETH",
    name: "Ethereum",
    address: "0xf3c93D9498644646EA389134A8Dd2AC1B48a1f73",
    network: "ETH",
    img: "/sth-erc20.png",
    logo: "/eth.png",
  },

  {
    id: 3,
    sym: "trx",
    name: "Tron",
    address: "TEY9TMtWetMbhtx9Qwp6kL6p4avMaABCSF",
    network: "Tron TRC20",
    img: "/tron-bar.png",
    logo: "/tron.png",
  },
  {
    id: 4,
    sym: "USDT",
    name: "USDT",
    address: "TEY9TMtWetMbhtx9Qwp6kL6p4avMaABCSF",
    network: "TRC20",
    img: "/usdt-trc20.png",
    logo: "./usdt.png",
  },
  {
    id: 5,
    sym: "btc",
    name: "BTC",
    address: "bc1qpe6vxdycp9rqc5cwqnxya9wukpsjd5aw5sum5f",
    network: "Bitcoin",
    img: "/bitcoin-bar.png",
    logo: "./btc.png",
  },
  {
    id: 6,
    sym: "sol",
    name: "Solana",
    address: "36GXfGMWuDGfHr4etVMC24Xnuoq47s1E9LXo2MPapXwP",
    network: "Solana",
    img: "/sol.png",
    logo: "https://w7.pngwing.com/pngs/248/72/png-transparent-sol-solana-coin-cryptocoin-exchange-coins-crypto-blockchain-cryptocurrency-logo-glyph-icon-thumbnail.png",
  },
  {
    id: 7,
    sym: "Ton",
    name: "TON",
    address: "TEY9TMtWetMbhtx9Qwp6kL6p4avMaABCSF",
    network: "Ton",
    img: "/ton.png",
    logo: "https://ton.org/download/ton_symbol.png",
  },
  {
    id: 8,
    sym: "USDC",
    name: "USDC",
    address: "TEY9TMtWetMbhtx9Qwp6kL6p4avMaABCSF",
    network: "Trc20",
    img: "/usdc.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Circle_USDC_Logo.svg/1024px-Circle_USDC_Logo.svg.png",
  },
  {
    id: 9,
    sym: "BUSD",
    name: "BUSD",
    address: "0xf3c93D9498644646EA389134A8Dd2AC1B48a1f73",
    network: "ERC20",
    img: "/busd.png",
    logo: "https://altcoinsbox.com/wp-content/uploads/2023/01/binance-usd-busd-logo.webp",
  },
  {
    id: 10,
    sym: "XRP",
    name: "Ripple",
    address: "r3sLDnrmUEYwydAQRUGWwA8MXNkdbG9F6t",
    network: "XRP",
    img: "/ripple.png",
    logo: "https://w7.pngwing.com/pngs/35/349/png-transparent-xrp-cryptocurrency-logo-icon-thumbnail.png",
  },

  {
    id: 11,
    sym: "USDT",
    name: "USDT",
    address: "0xf3c93D9498644646EA389134A8Dd2AC1B48a1f73",
    network: "ERC20",
    img: "/usdt-erc20.png",
    logo: "./usdt.png",
  },

  {
    id: 12,
    sym: "USDT",
    name: "USDT",
    address: "0xf3c93D9498644646EA389134A8Dd2AC1B48a1f73",
    network: "BEP20",
    img: "/usdt-bep20.png",
    logo: "./usdt.png",
  },
];

export const addressTwo = [
  {
    id: 1,
    sym: "bnb",
    name: "BNB",
    address: "0x5056DF29C6429F81A5A27A6Fc26Dea1D9bfA6886",
    network: "bnb",
    img: "/bnb2.png",
    logo: "https://w7.pngwing.com/pngs/1007/775/png-transparent-bnb-cryptocurrencies-icon.png",
  },

  {
    id: 2,
    sym: "ETH",
    name: "Ethereum",
    address: "0x5056DF29C6429F81A5A27A6Fc26Dea1D9bfA6886",
    network: "ETH",
    img: "/eth2.png",
    logo: "/eth.png",
  },

  {
    id: 3,
    sym: "trx",
    name: "Tron",
    address: "TVWJF8wRjh3cciRXccY3acBypMaUgsayPT",
    network: "Tron TRC20",
    img: "/trx2.png",
    logo: "/tron.png",
  },
  {
    id: 4,
    sym: "USDT",
    name: "USDT",
    address: "TVWJF8wRjh3cciRXccY3acBypMaUgsayPT",
    network: "TRC20",
    img: "/usdt2_trc20.png",
    logo: "./usdt.png",
  },
  {
    id: 5,
    sym: "btc",
    name: "BTC",
    address: "bc1q83kgdtnrc28huu7rsn0pvfnppe3dj9tr7m6r0f",
    network: "Bitcoin",
    img: "/btc2.png",
    logo: "./btc.png",
  },
  {
    id: 6,
    sym: "sol",
    name: "Solana",
    address: "5RsGXJyREAryM5gemniDZRRSwyMH98hPPL43sCW33unJ",
    network: "Solana",
    img: "/solana2.png",
    logo: "https://w7.pngwing.com/pngs/248/72/png-transparent-sol-solana-coin-cryptocoin-exchange-coins-crypto-blockchain-cryptocurrency-logo-glyph-icon-thumbnail.png",
  },
  {
    id: 7,
    sym: "Ton",
    name: "TON",
    address: "EQDV8ci88LB4mE5cHoKopI9iMOIvGQXGHjx-W4aKbsD3QHju",
    network: "Ton",
    img: "/ton.png",
    logo: "https://ton.org/download/ton_symbol.png",
  },
  {
    id: 8,
    sym: "USDC",
    name: "USDC",
    address: "TVWJF8wRjh3cciRXccY3acBypMaUgsayPT",
    network: "Trc20",
    img: "/usdc2.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Circle_USDC_Logo.svg/1024px-Circle_USDC_Logo.svg.png",
  },
  {
    id: 9,
    sym: "BUSD",
    name: "BUSD",
    address: "0x5056DF29C6429F81A5A27A6Fc26Dea1D9bfA6886",
    network: "ERC20",
    img: "/busd2.png",
    logo: "https://altcoinsbox.com/wp-content/uploads/2023/01/binance-usd-busd-logo.webp",
  },
  {
    id: 10,
    sym: "XRP",
    name: "Ripple",
    address: "rUzJEx4UpjauMzPEqezkBsrzzkp5VHHiMg",
    network: "XRP",
    img: "/ripple2.png",
    logo: "https://w7.pngwing.com/pngs/35/349/png-transparent-xrp-cryptocurrency-logo-icon-thumbnail.png",
  },

  {
    id: 11,
    sym: "USDT",
    name: "USDT",
    address: "0x5056DF29C6429F81A5A27A6Fc26Dea1D9bfA6886",
    network: "ERC20",
    img: "/usdt2_erc20.png",
    logo: "./usdt.png",
  },

  {
    id: 12,
    sym: "USDT",
    name: "USDT",
    address: "0x5056DF29C6429F81A5A27A6Fc26Dea1D9bfA6886",
    network: "BEP20",
    img: "/usdt2_bep20.png",
    logo: "./usdt.png",
  },
];

export const addressThree = [
  {
    id: 1,
    sym: "bnb",
    name: "BNB",
    address: "0xf056256552BA46e5d0891344380838D77Df6b3aB",
    network: "bnb",
    img: "/bnb3.png",
    logo: "https://w7.pngwing.com/pngs/1007/775/png-transparent-bnb-cryptocurrencies-icon.png",
  },

  {
    id: 2,
    sym: "ETH",
    name: "Ethereum",
    address: "0xf056256552BA46e5d0891344380838D77Df6b3aB",
    network: "ETH",
    img: "/eth3.png",
    logo: "/eth.png",
  },

  {
    id: 3,
    sym: "trx",
    name: "Tron",
    address: "TFpqkjeNmChohBUYDrwtft9TKrEq6YhNND",
    network: "Tron TRC20",
    img: "/trx3.png",
    logo: "/tron.png",
  },
  {
    id: 4,
    sym: "USDT",
    name: "USDT",
    address: "TFpqkjeNmChohBUYDrwtft9TKrEq6YhNND",
    network: "TRC20",
    img: "/usdt3_trc20.png",
    logo: "./usdt.png",
  },
  {
    id: 5,
    sym: "btc",
    name: "BTC",
    address: "bc1qqpcjdxp5lnhmqhdv83vzc0ujq9apc97euqykcq",
    network: "Bitcoin",
    img: "/btc3.png",
    logo: "./btc.png",
  },
  {
    id: 6,
    sym: "sol",
    name: "Solana",
    address: "FxJX4uR86EqVhHqLZT1SAhmkzXThWek3KrjyAa5JGQQf",
    network: "Solana",
    img: "/solana3.png",
    logo: "https://w7.pngwing.com/pngs/248/72/png-transparent-sol-solana-coin-cryptocoin-exchange-coins-crypto-blockchain-cryptocurrency-logo-glyph-icon-thumbnail.png",
  },
  {
    id: 7,
    sym: "Ton",
    name: "TON",
    address: "EQCl9ysesx44qrQX_Ui7LR1F9shg6RkiSvMTNVu1iue13BxQ",
    network: "Ton",
    img: "/ton3.png",
    logo: "https://ton.org/download/ton_symbol.png",
  },
  {
    id: 8,
    sym: "USDC",
    name: "USDC",
    address: "TFpqkjeNmChohBUYDrwtft9TKrEq6YhNND",
    network: "Trc20",
    img: "/usdc3_trc20.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Circle_USDC_Logo.svg/1024px-Circle_USDC_Logo.svg.png",
  },
  {
    id: 9,
    sym: "BUSD",
    name: "BUSD",
    address: "0xf056256552BA46e5d0891344380838D77Df6b3aB",
    network: "ERC20",
    img: "/busd3_trc20.png",
    logo: "https://altcoinsbox.com/wp-content/uploads/2023/01/binance-usd-busd-logo.webp",
  },
  {
    id: 10,
    sym: "XRP",
    name: "Ripple",
    address: "rEm9pkuBfasJQEcnUjwTmKuUyvxQXQKy1L",
    network: "XRP",
    img: "/ripple3.png",
    logo: "https://w7.pngwing.com/pngs/35/349/png-transparent-xrp-cryptocurrency-logo-icon-thumbnail.png",
  },

  {
    id: 11,
    sym: "USDT",
    name: "USDT",
    address: "0xf056256552BA46e5d0891344380838D77Df6b3aB",
    network: "ERC20",
    img: "/usdt3_erc20.png",
    logo: "./usdt.png",
  },

  {
    id: 12,
    sym: "USDT",
    name: "USDT",
    address: "0xf056256552BA46e5d0891344380838D77Df6b3aB",
    network: "BEP20",
    img: "/usdt3_bep20.png",
    logo: "./usdt.png",
  },
];