export const addresses = [
  {
    id: 1,
    sym: "bnb",
    name: "BNB",
    address: "0x423A6503304df12541467A2f7Aead1D9059b2BB4",
    network: "bnb",
    img: "/bnb.png",
    logo: "https://w7.pngwing.com/pngs/1007/775/png-transparent-bnb-cryptocurrencies-icon.png",
  },

  {
    id: 2,
    sym: "ETH",
    name: "Ethereum",
    address: "0x423A6503304df12541467A2f7Aead1D9059b2BB4",
    network: "ETH",
    img: "/sth-erc20.png",
    logo: "/eth.png",
  },

  {
    id: 3,
    sym: "trx",
    name: "Tron",
    address: "TN5r26bDkaNeL1eN9cNthYbBWud6N9LyiN",
    network: "Tron TRC20",
    img: "/tron-bar.png",
    logo: "/tron.png",
  },
  {
    id: 4,
    sym: "USDT",
    name: "USDT",
    address: "TN5r26bDkaNeL1eN9cNthYbBWud6N9LyiN",
    network: "TRC20",
    img: "/usdt-trc20.png",
    logo: "./usdt.png",
  },
  {
    id: 5,
    sym: "btc",
    name: "BTC",
    address: "bc1qpu7w3fw9x347waph4eexfjnf7qtkl0thp2r5sj",
    network: "Bitcoin",
    img: "/bitcoin-bar.png",
    logo: "./btc.png",
  },
  {
    id: 6,
    sym: "sol",
    name: "Solana",
    address: "ELmT5EJVn7aJdH7PLePfajuyLbU1ANAtgKa9YxjiqqVX",
    network: "Solana",
    img: "/sol.png",
    logo: "https://w7.pngwing.com/pngs/248/72/png-transparent-sol-solana-coin-cryptocoin-exchange-coins-crypto-blockchain-cryptocurrency-logo-glyph-icon-thumbnail.png",
  },
  {
    id: 7,
    sym: "Ton",
    name: "TON",
    address: "EQBKFiM1Py9pcBoh8ORaT2IlOy9YLRvHW940pm8QJ7su14",
    network: "Ton",
    img: "/ton.png",
    logo: "https://ton.org/download/ton_symbol.png",
  },
  {
    id: 8,
    sym: "USDC",
    name: "USDC",
    address: "TN5r26bDkaNeL1eN9cNthYbBWud6N9LyiN",
    network: "Trc20",
    img: "/usdc.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Circle_USDC_Logo.svg/1024px-Circle_USDC_Logo.svg.png",
  },
  {
    id: 9,
    sym: "BUSD",
    name: "BUSD",
    address: "0x423A6503304df12541467A2f7Aead1D9059b2BB4",
    network: "ERC20",
    img: "/busd.png",
    logo: "https://altcoinsbox.com/wp-content/uploads/2023/01/binance-usd-busd-logo.webp",
  },
  {
    id: 10,
    sym: "XRP",
    name: "Ripple",
    address: "r4VN8yVkz7gGfgheF3eUi4q1ZWiPkyryrG",
    network: "XRP",
    img: "/ripple.png",
    logo: "https://w7.pngwing.com/pngs/35/349/png-transparent-xrp-cryptocurrency-logo-icon-thumbnail.png",
  },

  {
    id: 11,
    sym: "USDT",
    name: "USDT",
    address: "0x423A6503304df12541467A2f7Aead1D9059b2BB4",
    network: "ERC20",
    img: "/usdt-erc20.png",
    logo: "./usdt.png",
  },

  {
    id: 12,
    sym: "USDT",
    name: "USDT",
    address: "0x423A6503304df12541467A2f7Aead1D9059b2BB4",
    network: "BEP20",
    img: "/usdt-bep20.png",
    logo: "./usdt.png",
  },
];
