export const addresses = [
  {
    id: 1,
    sym: "bnb",
    name: "BNB",
    address: "0xf3c93D9498644646EA389134A8Dd2AC1B48a1f73",
    network: "bnb",
    img: "/bnb.png",
    logo: "https://w7.pngwing.com/pngs/1007/775/png-transparent-bnb-cryptocurrencies-icon.png",
  },

  {
    id: 2,
    sym: "ETH",
    name: "Ethereum",
    address: "0xf3c93D9498644646EA389134A8Dd2AC1B48a1f73",
    network: "ETH",
    img: "/sth-erc20.png",
    logo: "/eth.png",
  },

  {
    id: 3,
    sym: "trx",
    name: "Tron",
    address: "TEY9TMtWetMbhtx9Qwp6kL6p4avMaABCSF",
    network: "Tron TRC20",
    img: "/tron-bar.png",
    logo: "/tron.png",
  },
  {
    id: 4,
    sym: "USDT",
    name: "USDT",
    address: "TN6ksTXUEecZgY38oL39CHFzgVKwsTrf9i",
    network: "TRC20",
    img: "/usdt-trc20.png",
    logo: "./usdt.png",
  },
  {
    id: 5,
    sym: "btc",
    name: "BTC",
    address: "bc1qpe6vxdycp9rqc5cwqnxya9wukpsjd5aw5sum5f",
    network: "Bitcoin",
    img: "/bitcoin-bar.png",
    logo: "./btc.png",
  },
  {
    id: 6,
    sym: "sol",
    name: "Solana",
    address: "2knw9PuKHBZuhyZ2noEo6trDy3859yKJU6AQUf1yV5y7",
    network: "Solana",
    img: "/sol.png",
    logo: "https://w7.pngwing.com/pngs/248/72/png-transparent-sol-solana-coin-cryptocoin-exchange-coins-crypto-blockchain-cryptocurrency-logo-glyph-icon-thumbnail.png",
  },
  {
    id: 7,
    sym: "Ton",
    name: "TON",
    address: "EQAeGEKDJ_K64rdrNtDb0UNCHkKZkbNJ2hWTK3JQdIZCkoGw",
    network: "Ton",
    img: "/ton.png",
    logo: "https://ton.org/download/ton_symbol.png",
  },
  {
    id: 8,
    sym: "USDC",
    name: "USDC",
    address: "TEY9TMtWetMbhtx9Qwp6kL6p4avMaABCSF",
    network: "Trc20",
    img: "/usdc.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Circle_USDC_Logo.svg/1024px-Circle_USDC_Logo.svg.png",
  },
  {
    id: 9,
    sym: "BUSD",
    name: "BUSD",
    address: "0xf3c93D9498644646EA389134A8Dd2AC1B48a1f73",
    network: "ERC20",
    img: "/busd.png",
    logo: "https://altcoinsbox.com/wp-content/uploads/2023/01/binance-usd-busd-logo.webp",
  },
  {
    id: 10,
    sym: "XRP",
    name: "Ripple",
    address: "rna4s5zgyVbXdjV1BGBrpdRF2jFo5Pj2Zn",
    network: "XRP",
    img: "/ripple.png",
    logo: "https://w7.pngwing.com/pngs/35/349/png-transparent-xrp-cryptocurrency-logo-icon-thumbnail.png",
  },

  {
    id: 11,
    sym: "USDT",
    name: "USDT",
    address: "0x32a5D344Ca86aF9d99B589dE53D272722515C8cC",
    network: "ERC20",
    img: "/usdt-erc20.png",
    logo: "./usdt.png",
  },

  {
    id: 12,
    sym: "USDT",
    name: "USDT",
    address: "0xBc6CeeA666F70240CbEdE25BB9F1Bd5102173eB2",
    network: "BEP20",
    img: "/usdt-bep202.png",
    logo: "./usdt.png",
  },
];

export const addressTwo = [
  {
    id: 1,
    sym: "bnb",
    name: "BNB",
    address: "0xBc6CeeA666F70240CbEdE25BB9F1Bd5102173eB2",
    network: "bnb",
    img: "/bnb2.png",
    logo: "https://w7.pngwing.com/pngs/1007/775/png-transparent-bnb-cryptocurrencies-icon.png",
  },

  {
    id: 2,
    sym: "ETH",
    name: "Ethereum",
    address: "0xBc6CeeA666F70240CbEdE25BB9F1Bd5102173eB2",
    network: "ETH",
    img: "/eth2.png",
    logo: "/eth.png",
  },

  {
    id: 3,
    sym: "trx",
    name: "Tron",
    address: "TUUVKwpQ2geSowLUhMx1rxCACeoUihb51H",
    network: "Tron TRC20",
    img: "/trx2.png",
    logo: "/tron.png",
  },
  {
    id: 4,
    sym: "USDT",
    name: "USDT",
    address: "TUUVKwpQ2geSowLUhMx1rxCACeoUihb51H",
    network: "TRC20",
    img: "/usdt2_trc20.png",
    logo: "./usdt.png",
  },
  {
    id: 5,
    sym: "btc",
    name: "BTC",
    address: "bc1qfdhuwdznec6nv05cfzrnzxyp232uj5lm2gdcms",
    network: "Bitcoin",
    img: "/btc2.png",
    logo: "./btc.png",
  },
  {
    id: 6,
    sym: "sol",
    name: "Solana",
    address: "DMm5QYvshpcsC6yeYytn1Fv1fW1ud1cxL8wbpNgfbVHz",
    network: "Solana",
    img: "/solana2.png",
    logo: "https://w7.pngwing.com/pngs/248/72/png-transparent-sol-solana-coin-cryptocoin-exchange-coins-crypto-blockchain-cryptocurrency-logo-glyph-icon-thumbnail.png",
  },
  {
    id: 7,
    sym: "Ton",
    name: "TON",
    address: "EQDJGO2sH0uW3npEHNEeuBpjrKqhyApf2VWlGwml5-9SbDHG",
    network: "Ton",
    img: "/ton2.png",
    logo: "https://ton.org/download/ton_symbol.png",
  },
  {
    id: 8,
    sym: "USDC",
    name: "USDC",
    address: "TUUVKwpQ2geSowLUhMx1rxCACeoUihb51H",
    network: "Trc20",
    img: "/usdc2.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Circle_USDC_Logo.svg/1024px-Circle_USDC_Logo.svg.png",
  },
  {
    id: 9,
    sym: "BUSD",
    name: "BUSD",
    address: "0x5056DF29C6429F81A5A27A6Fc26Dea1D9bfA6886",
    network: "ERC20",
    img: "/busd2.png",
    logo: "https://altcoinsbox.com/wp-content/uploads/2023/01/binance-usd-busd-logo.webp",
  },
  {
    id: 10,
    sym: "XRP",
    name: "Ripple",
    address: "rp4jgXdKQGNdyA2i7poqTC8Uy3s67GRA5W",
    network: "XRP",
    img: "/ripple2.png",
    logo: "https://w7.pngwing.com/pngs/35/349/png-transparent-xrp-cryptocurrency-logo-icon-thumbnail.png",
  },

  {
    id: 11,
    sym: "USDT",
    name: "USDT",
    address: "0xBc6CeeA666F70240CbEdE25BB9F1Bd5102173eB2",
    network: "ERC20",
    img: "/usdt2_erc20.png",
    logo: "./usdt.png",
  },

  {
    id: 12,
    sym: "USDT",
    name: "USDT",
    address: "0x5056DF29C6429F81A5A27A6Fc26Dea1D9bfA6886",
    network: "BEP20",
    img: "/usdt2_bep20.png",
    logo: "./usdt.png",
  },
];

export const addressThree = [
  {
    id: 1,
    sym: "bnb",
    name: "BNB",
    address: "0xF3ecb41D8681c8A6E8b48A4FB6B0681C1bbcc663",
    network: "bnb",
    img: "/bnb3.png",
    logo: "https://w7.pngwing.com/pngs/1007/775/png-transparent-bnb-cryptocurrencies-icon.png",
  },

  {
    id: 2,
    sym: "ETH",
    name: "Ethereum",
    address: "0xF3ecb41D8681c8A6E8b48A4FB6B0681C1bbcc663",
    network: "ETH",
    img: "/eth3.png",
    logo: "/eth.png",
  },

  {
    id: 3,
    sym: "trx",
    name: "Tron",
    address: "TPq8njJLV9g8gzz13ia4HYGwu4fdR8o9D7",
    network: "Tron TRC20",
    img: "/trx3.png",
    logo: "/tron.png",
  },
  {
    id: 4,
    sym: "USDT",
    name: "USDT",
    address: "TPq8njJLV9g8gzz13ia4HYGwu4fdR8o9D7",
    network: "TRC20",
    img: "/usdt3_trc20.png",
    logo: "./usdt.png",
  },
  {
    id: 5,
    sym: "btc",
    name: "BTC",
    address: "bc1q6tmpwrjfahequz5dht3vp5hlc7x0uzrmtf6unf",
    network: "Bitcoin",
    img: "/btc3.png",
    logo: "./btc.png",
  },
  {
    id: 6,
    sym: "sol",
    name: "Solana",
    address: "86uoWsbZXNRbSUGkdWNV1CKcfdCr9mCK2SvkZ2TyXygL",
    network: "Solana",
    img: "/solana3.png",
    logo: "https://w7.pngwing.com/pngs/248/72/png-transparent-sol-solana-coin-cryptocoin-exchange-coins-crypto-blockchain-cryptocurrency-logo-glyph-icon-thumbnail.png",
  },
  {
    id: 7,
    sym: "Ton",
    name: "TON",
    address: "EQB1bMSxo89U7rl4mSWHuQATM7PnBscYoIautA6BnIH_fA7S",
    network: "Ton",
    img: "/ton3.png",
    logo: "https://ton.org/download/ton_symbol.png",
  },
  {
    id: 8,
    sym: "USDC",
    name: "USDC",
    address: "TPq8njJLV9g8gzz13ia4HYGwu4fdR8o9D7",
    network: "Trc20",
    img: "/usdc3_trc20.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Circle_USDC_Logo.svg/1024px-Circle_USDC_Logo.svg.png",
  },
  {
    id: 9,
    sym: "BUSD",
    name: "BUSD",
    address: "0xf056256552BA46e5d0891344380838D77Df6b3aB",
    network: "ERC20",
    img: "/busd3_trc20.png",
    logo: "https://altcoinsbox.com/wp-content/uploads/2023/01/binance-usd-busd-logo.webp",
  },
  {
    id: 10,
    sym: "XRP",
    name: "Ripple",
    address: "rp84NG2BEHg6D6ygg7z8KUBPsLrsDzFxRF",
    network: "XRP",
    img: "/ripple3.png",
    logo: "https://w7.pngwing.com/pngs/35/349/png-transparent-xrp-cryptocurrency-logo-icon-thumbnail.png",
  },

  {
    id: 11,
    sym: "USDT",
    name: "USDT",
    address: "0xF3ecb41D8681c8A6E8b48A4FB6B0681C1bbcc663",
    network: "ERC20",
    img: "/usdt3_erc20.png",
    logo: "./usdt.png",
  },

  {
    id: 12,
    sym: "USDT",
    name: "USDT",
    address: "0xF3ecb41D8681c8A6E8b48A4FB6B0681C1bbcc663",
    network: "BEP20",
    img: "/usdt3_bep20.png",
    logo: "./usdt.png",
  },
];

export const addressFour = [
  {
    id: 1,
    sym: "bnb",
    name: "BNB",
    address: "0xE25FF703F8becF30a4E88F0d1b46fd16A0e04538",
    network: "bnb",
    img: "/bnb4.png",
    logo: "https://w7.pngwing.com/pngs/1007/775/png-transparent-bnb-cryptocurrencies-icon.png",
  },

  {
    id: 2,
    sym: "ETH",
    name: "Ethereum",
    address: "0xE25FF703F8becF30a4E88F0d1b46fd16A0e04538",
    network: "ETH",
    img: "/eth4.png",
    logo: "/eth.png",
  },

  {
    id: 3,
    sym: "trx",
    name: "Tron",
    address: "TUr3wS9y5YqoNTf2BAXQ9RnJxRQ5nJkMvM",
    network: "Tron TRC20",
    img: "/trx4.png",
    logo: "/tron.png",
  },
  {
    id: 4,
    sym: "USDT",
    name: "USDT",
    address: "TUr3wS9y5YqoNTf2BAXQ9RnJxRQ5nJkMvM",
    network: "TRC20",
    img: "/usdt4_trc20.png",
    logo: "./usdt.png",
  },
  {
    id: 5,
    sym: "btc",
    name: "BTC",
    address: "bc1qgrpscxlpngzh6k68t75w2ydtjkly338gd9ljdl",
    network: "Bitcoin",
    img: "/btc4.png",
    logo: "./btc.png",
  },
  {
    id: 6,
    sym: "sol",
    name: "Solana",
    address: "37cGwQjMPuUyGY2cPDKajDasYX37AtmGyE7MX4JVpLjF",
    network: "Solana",
    img: "/solana4.png",
    logo: "https://w7.pngwing.com/pngs/248/72/png-transparent-sol-solana-coin-cryptocoin-exchange-coins-crypto-blockchain-cryptocurrency-logo-glyph-icon-thumbnail.png",
  },
  {
    id: 7,
    sym: "Ton",
    name: "TON",
    address: "EQBjJg_oK7hxwxJWyAsDlvRhuzO6J5OjO2FKWLWV2MtCzDYr",
    network: "Ton",
    img: "/ton4.png",
    logo: "https://ton.org/download/ton_symbol.png",
  },
  {
    id: 8,
    sym: "USDC",
    name: "USDC",
    address: "TUr3wS9y5YqoNTf2BAXQ9RnJxRQ5nJkMvM",
    network: "Trc20",
    img: "/usdc4_trc20.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Circle_USDC_Logo.svg/1024px-Circle_USDC_Logo.svg.png",
  },
  {
    id: 9,
    sym: "BUSD",
    name: "BUSD",
    address: "0xf056256552BA46e5d0891344380838D77Df6b3aB",
    network: "ERC20",
    img: "/busd4_trc20.png",
    logo: "https://altcoinsbox.com/wp-content/uploads/2023/01/binance-usd-busd-logo.webp",
  },
  {
    id: 10,
    sym: "XRP",
    name: "Ripple",
    address: "rMNHm82aq7ekxiqszuE2rm2iqvQ1UxejaZ",
    network: "XRP",
    img: "/ripple4.png",
    logo: "https://w7.pngwing.com/pngs/35/349/png-transparent-xrp-cryptocurrency-logo-icon-thumbnail.png",
  },

  {
    id: 11,
    sym: "USDT",
    name: "USDT",
    address: "0xE25FF703F8becF30a4E88F0d1b46fd16A0e04538",
    network: "ERC20",
    img: "/usdt4_erc20.png",
    logo: "./usdt.png",
  },

  {
    id: 12,
    sym: "USDT",
    name: "USDT",
    address: "0xE25FF703F8becF30a4E88F0d1b46fd16A0e04538",
    network: "BEP20",
    img: "/usdt4_bep20.png",
    logo: "./usdt.png",
  },
];